### ISSUE TITLE
Error with exceeded amounts? 

### ISSUE THREAD

**Issue by zavodil** [near/rainbow-bridge-frontend#113] opened 2021-02-24 16:00 UTC
found that error when I tried to transfer more tokens than I had. 

![Clip2net_210224175643](https://user-images.githubusercontent.com/38926321/109027793-d476ed80-76c9-11eb-85a0-a369b6d20b85.png)

Tried to send 100 when I had 99

Got a metamask error, if ignore it then tx failure https://ropsten.etherscan.io/tx/0x1f4883b28b4412b74524a1e994d79922ffd0c17df468216d13583552c4aa4c5d

**Comment by paouvrard** [comment] 2021-02-25 04:46
Thank you for this ! The issue is fixed. 

It is not totally perfect yet. The amount input field will prevent the user from transferring more than their balance. But the html input field compares rounded numbers so dust amounts cannot be transferred without implementing a new custom check.
I think this can be implemented when we decide to add a MAX button which sets all the balance including dust.

**Closed** 2021-02-26 13:10 UTC
Labels: P2, bug
